### ISSUE TITLE
Is there any oxt build file that ready to use?

### ISSUE THREAD

**Issue by raniaamina** [pmossie/-QuranLOAddon#1]
Hi,

I can't build this extension since i have no experience in Java. I tried to build in Eclipse but no results. Is there any oxt build file that ready to use? And is this extensions support latest version of LibreOffice?

**Comment by bagustris** [comment]
@raniaamina 
You can download from here: https://extensions.libreoffice.org/en/extensions/show/1102

**Comment by raniaamina** [comment]
Thanks, i'll check it

**Comment by pmossie** [comment]
Although, I have not build it for the latest version, the version on the plugin website should work with 24
